version: '2'

services:

    pub.restapi:
        image: idgis/arcgis-restapi-ov:0.1.1
        restart: always
        expose:
            - "8081"
        ports:
            - "${IP_ADDR}:8081:8081"
        environment:
            - DB_USER=publisher
            - DB_PASSWORD=${PUB_PG_PASSWORD}
            - DB_PORT=5432
            - DB_HOST=ov_pub.db_1